[package]
version = "0.1.0"
authors = ["Karl Grasegger <51945878+grasegger@users.noreply.github.com>"]
edition = "2018"
name = "example"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
anna = {version = "~0", path = "../anna" }
wasm-bindgen = "~0.2"
js-sys = "~0.3"
console_error_panic_hook = "~0.1"
async-trait = "~0.1"
wasm-bindgen-futures = "~0.4"
horrorshow = "~0.8"

[dependencies.web-sys]
version = "~0.3"
features = ["console"]